### ISSUE TITLE
Are we using the best practices for the Lambda handler?

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/aws-microservices-deploy-options#140]
https://github.com/aws-samples/aws-microservices-deploy-options/blob/master/services/greeting/src/main/java/org/aws/samples/compute/greeting/GreetingHandler.java is the handler for `greeting` service.

Can this be further simplified? Are we following the best practices here?

@SAPessi @allinwonder what do you think?

**Comment by SAPessi** [comment]
I don't think it can, at least if we want to use JAX-RS.

I tend to think of Lambda as a generic compute platform. When building APIs, I would pick JAX-RS because:
1. Well understood and defined specs with routing logic I can trust instead of building my own
2. Easy to make the code portable and move it in and out of Lambda as needed

Using a single function to handle multiple endpoints Increases likelihood of container reuse - and therefore reduces the occurrence of cold starts. Here we get into a philosophical discussion: Lambda's are meant to be single-task functions. However, I would postulate that this has more to do on how you organize your organization to work on microservices. So long as a Lambda function is specific to one microservice and a single team works on it, this no different than working on containerized/EC2 microservices.

**Comment by arun-gupta** [comment]
@SAPessi thanks for your feedback!

@allinwonder any thoughts?

**Comment by allinwonder** [comment]
@arun-gupta I agree that if we use the JAX-RS framework, then it is following a best practice. I agree with @SAPessi on the point that using a standard framework can give the application an advantage in its portability. It makes feasible to migrate between different platforms with least effort. 

On the other hand, I am not 100% align to SAPessi's point of routing logic. Because the design of AWS API Gateway is to fulfill the routing, validation, transformation, and auth. It takes care of these responsibilities for the application, and developers can focus on developing business logic.

In an ideal design, a function should follow a principal to do one thing and do it well. Each endpoint presents a microservice API that is hosted by API Gateway. A microservice can consist of multiple Lambda functions. In most cases, a service uses multiple Lambda functions to serve incoming requests. Sometimes during the fulfillment of a request, if the Lambda function needs to communicate with other modules within a service (in most cases are other Lambda functions), an AWS StepFunctions can be used to orchestrate the process. In this way, it breaks down the complexity of Lambda functions further.

To reduce the latency of cold start, it should be addressed on the platform instead of the application. With the maturity of Lambda service in the past years, I have seen improvements are made to reduce this latency, and I am confident that Lambda service will continue to grow and mature. With this in mind, developers can focus more on the best practice of design and develop their applications.

**Comment by SAPessi** [comment]
@allinwonder  I agree that functions should perform a single task - but the answer here rests on what the definition of "single task" is. For data processing, such as function consuming a Kiensis stream or S3 events, this is easy enough and I agree with your plan of 1 function = 1 task. 

For APIs, I feel the definition is slightly different. Let's say we are writing a "names" API/resource with a GET and POST methods - the methods retrieve and insert names from DynamoDB. In this case, I would think of names management as the task. The two methods are likely to share a lot of common code: the POJO, validation, fine-grained authorization. Exception for the insert/get call, almost all of the code is shared. In that case, I don't see the value of splitting this into two separate functions - bugs in the function are likely to be in the common library since the "frontend" code is such thin shim. Also, it's unlikely that organizationally I'll have two separate teams working on each method. I think in the case of APIs the definition of single task becomes a lot more fluid and there is no one-approach-fits all.

**Comment by allinwonder** [comment]
@SAPessi I can’t agree more that there is no one-approach-fits all, it all depends. The number of Lambda functions that supports an API can be vary, it can do all the CRUD in one function and use library to handle business logic. I also see production code that splits a CRUD in seperated functions that can achieve more sophisticated deployment strategy and reduce risks in function failures. 

@arun-gupta, I think the function we implemented here reached the goal to demonstrate how to use a framework to deploy into multiple platforms. The how and what are the best practices to use in different contexts should be captured in a different place, for example a talk/workshop, to let audience expose to different scenarios and choose a right fit base on what is the goal they want to achieve.

**Comment by arun-gupta** [comment]
Thanks @SAPessi @allinwonder for a wonderful discussion. Agreed that we should demonstrate different Serverless architecture patterns in a different repo.

Will close this issue.
