### ISSUE TITLE
Deploy k8s application using Docker Compose

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/aws-microservices-deploy-options#62]
Add a new way to deploy Kubernetes application using Docker Compose

**Comment by arun-gupta** [comment]
Use `--orchestrator kubernetes` for correct platform

**Comment by arun-gupta** [comment]
@swindle @christopherhein do you still plan to take a look at it?

**Comment by arun-gupta** [comment]
Can `DOCKER_ORCHESTRATOR=kubernetes docker stack deploy --compose-file=docker-compose.yaml myapp` be used to deploy to a k8s cluster running on AWS?

It is giving the following error `could not find compose.docker.com api. Install it on your cluster first`.

**Comment by mikegcoleman** [comment]
Unfortunately today there isn't a way to use Docker Compose with a native Kubernetes cluster. We (Docker) have integration with our Docker Desktop products and with Docker Universal Control Plane because in both those cases we're setting up the Kubernetes cluster - but there is no way to add this functionality to a Kubernetes cluster deployed in some other manner.
